version: "3"

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: always
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: "0.25"  # Giới hạn sử dụng 50% CPU
          memory: "128M"  # Giới hạn sử dụng 256 MB RAM
        reservations:
          cpus: "0.15"  # Đảm bảo ít nhất 25% CPU
          memory: "64M"  # Đảm bảo ít nhất 128 MB RAM


  kafka:
    image: "bitnami/kafka:latest"
    container_name: kafka
    user: root
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.120.26:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    restart: always
    networks:
      - app_network

networks:
  app_network:
    external: true
