global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # - job_name: 'backend-services'
  #   static_configs:
  #     - targets:
  #         - auth_service:8000
  #         - user_service:8080
  #         - data_service:8080
  #         - deeplearning_service:8000