version: '3.8'

services:
  data_service:
    image: caothi/data_service:latest
    container_name: data_service
    environment:
      - POSTGRESQL_HOST=$POSTGRESQL_HOST
      - POSTGRESQL_DB=$POSTGRESQL_DB
      - POSTGRESQL_USER=$POSTGRESQL_USER
      - POSTGRESQL_PASSWORD=$POSTGRESQL_PASSWORD
      - POSTGRESQL_PORT=$POSTGRESQL_PORT
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_DB=$MONGODB_DB
      - MONGODB_PORT=$MONGODB_PORT
      - MONGODB_HOST=$MONGODB_HOST
    restart: always
    networks:
      - app_network
    volumes:
      - /home/$USER/image/road:/app/roadImages/

networks:
  app_network:
    external: true