version: '3.8'

services:
  user_service:
    image: caothi/user_service:latest
    container_name: user_service
    environment:
      - POSTGRESQL_HOST=$POSTGRESQL_HOST
      - POSTGRESQL_DB=$POSTGRESQL_DB
      - POSTGRESQL_USER=$POSTGRESQL_USER
      - POSTGRESQL_PASSWORD=$POSTGRESQL_PASSWORD
      - POSTGRESQL_PORT=$POSTGRESQL_PORT
    restart: always
    networks:
      - app_network
    volumes:
      - /home/$USER/image/avata/:/app/avatar
      

networks:
  app_network:
    external: true
